import type { Metadata } from "next";

import SideNavBar from "@/components/sidebar/SideNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex h-[100vh]">
      <aside className="flex items-center justify-around h-full">
        <SideNavBar />
      </aside>
      {children}
    </main>
  );
}
